### ISSUE TITLE
[Keymap] .key files are not applied if containing some special characters like brackets or spaces

### ISSUE THREAD

**Issue by DrUm78** [FunKey-Project/FunKey-OS#16]
.key files are not applied if containing some special characters like "(", ")" or any space despite the confirmation in GMenu2X logs.

**To Reproduce**
1. Have any rom with spaces and/or brackets included in its name
2. Have a .key file with a different key mapping with the same name
3. Launch the game
4. Notice that the new key mapping is not applied

**Expected behavior**
.key files should be applied even with special characters.

**Comment by Michel-FK** [comment]
Corrected with comit https://github.com/FunKey-Project/FunKey-OS/commit/ffa1595cd3f5f5500dc8295b1a12c95245815f69

**Comment by DrUm78** [comment]
Fixed and verified!

**Comment by DrUm78** [comment]
@Michel-FK The bug still occurs with apostrophe character (" ' ").
